# Generated by Django 4.1.7 on 2023-04-05 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('episode', '0002_alter_playlist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
