# Generated by Django 4.1.7 on 2023-04-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('episode', '0003_alter_playlist_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='episode.episode')),
            ],
        ),
    ]
