# Generated by Django 4.1.7 on 2023-04-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0004_episodelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playmusic',
            name='play_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='episode.playlist'),
        ),
    ]
