# Generated by Django 4.1.7 on 2023-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0005_alter_playmusic_play_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='episodes',
            field=models.ManyToManyField(related_name='play_list', to='episode.episode'),
        ),
    ]
